### ISSUE TITLE
LAST BLOCKS FOUND SHOW WRONG DATES and TIMES

### ISSUE THREAD

**Issue by deeppurple72** [p2pool/p2pool#161]
I have noticed that several pools are showing the wrong dates/times for
the found blocks.

A pool just found a block Jan 28, 2014 16:59 GMT-0500 EST

but the last blocks list shows Jan 23, 2014 03:30 GMT-0500 EST

and its several pools doing this!

This confuses miners, and they leave pools when seeing this
making it look like pool hasnt found blocks in days, despite the fact
that it literally just found a block.

What could be causing this issue?
The computer's System time/date is correct, so is the CMOS time/date.

I'm baffled as to why its showing wrong times/dates

Please advise

( recent github version 13.9.4 and so did the prior version do this as well )

**Comment by CartmanSPC** [comment]
Sorry to rehash this old issue but it has started to become more and more of a problem.
I believe the issue is with the share chain's timestamps when a p2pool does not find a block for a long period of time.

I posted some more info and a bounty here:
https://bitcointalk.org/index.php?topic=18313.msg11899552#msg11899552

**Comment by forrestv** [comment]
Hmm, which altcoin is this for? My current theory is that the altcoin's P2Pool configuration is set such that the total hashrate of the pool isn't enough to make one share every `SHARE_PERIOD` amount of time, even with the minimum allowable difficulty (set by `MAX_TARGET`). Shares are each only allowed to move time forward by `2 * SHARE_PERIOD`.

**Comment by deeppurple72** [comment]
I believe the timestamps come from the block chain blocks... Perhaps it is related to the source code of the alt-coin and not a p2pool issue. Of course I could be wrong, but that's what I am thinking. I've experienced incorrect dates/times of found blocks only with some alt-coins, whereas other alt-coins appear to have correct timestamps.... I'm not a programmer, but have looked at alot of source code to setup p2pools in the past... I noticed people usually "fork" an existing alt-coin and change the name, and a few other parameters... Perhaps the alt-coins having timestamp issues might be related to "forking" a buggy source code?

On July 17, 2015 7:12:30 PM EDT, CartmanSPC <notifications@github.com> wrote:
>Sorry to rehash this old issue but it has started to become more and
>more of a problem.
>I believe the issue is with the share chain's timestamps when a p2pool
>does not find a block for a long period of time.
>
>I posted some more info and a bounty here:
>https://bitcointalk.org/index.php?topic=18313.msg11899552#msg11899552
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/forrestv/p2pool/issues/161#issuecomment-122441522

-- 
Sent from my Android device.

**Comment by Rav3nPL** [comment]
It it some P2Pool issue, it happens when pool rate is really low and/or there is no mining for "some" time (eg a day).
P2Pool is reading block header timestamps correctly, but somehow it is wrongly stored and displayed.

**Comment by deeppurple72** [comment]
Well if that's the case, it sounds like a python code issue.... Guess the code related to reading the last blocks timestamp needs review then.

On July 18, 2015 2:35:40 PM EDT, Rav3nPL <notifications@github.com> wrote:
>It it some P2Pool issue, it happens when pool rate is really low and/or
>there is no mining for "some" time (eg a day).
>P2Pool is reading block header timestamps correctly, but somehow it is
>wrongly stored and displayed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/forrestv/p2pool/issues/161#issuecomment-122576852

-- 
Sent from my Android device.

**Comment by deeppurple72** [comment]
BTW, is their an example of a specific alt-coin exhibiting this issue so it can be further investigated? Thanks.

On July 18, 2015 2:35:40 PM EDT, Rav3nPL <notifications@github.com> wrote:
>It it some P2Pool issue, it happens when pool rate is really low and/or
>there is no mining for "some" time (eg a day).
>P2Pool is reading block header timestamps correctly, but somehow it is
>wrongly stored and displayed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/forrestv/p2pool/issues/161#issuecomment-122576852

-- 
Sent from my Android device.

**Comment by Rav3nPL** [comment]
Pick some "easy" one, do separate pool, mine to find 1-2 blocks, stop mining for 1 day, mine again 1-2 blocks :P

**Comment by CartmanSPC** [comment]
This is happening with most of the coins at xpool.net unless they have a consistent hash rate above a certain amount. Source for xpool.net can be found here:
http://github.com/cartmanspc/p2pool

**Comment by CartmanSPC** [comment]
Thanks for your input forrestv. It made me realize that a p2pool needs to have at least one share every SHARE_PERIOD to keep the stored share time current.  It also made me realize that a block does not necessarily need to be found for it to catch up. With that information I can look at providing enough hash to each coin to keep the share chain's time current.
