### ISSUE TITLE
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers

### ISSUE THREAD

**Issue by whattheflux** [p2pool/p2pool#180]
Have never seen this before running p2pool for multiple different coins.
Have tried multiple different ports with no success.
? thoughts

**Comment by farsider350** [comment]
Bootstraps need updating.

**Comment by haarts** [comment]
I experience the same exception. What does it mean that 'Bootstraps need updating'? 
I'm not even sure this is a critical error. After displaying it the program happily seems to continue.
