### ISSUE TITLE
Request for Recent Blocks found

### ISSUE THREAD

**Issue by smoothrunnings** [p2pool/p2pool#182]
Can there be an option for bitcoin nodes to display the recent blocks found for a longer period of time? say up to a week instead of 24 hours?

Thanks,

**Comment by devlin85** [comment]
That's actually all backwards.. You need to adjust the CHAIN_LENGTH not the REAL_CHAIN_LENGTH, REAL_CHAIN_LENGTH will disconnect you from an existing pool network as the REAL_CHAIN_LENGTH needs to match all the nodes in the pool. Set the CHAIN_LENGTH to 7*24*60*60//10 and it should keep for a week.

This is in the bitcoin.py file:

# CHAIN_LENGTH = number of shares back client keeps
# REAL_CHAIN_LENGTH = maximum number of shares back client uses to compute payout
# REAL_CHAIN_LENGTH must always be <= CHAIN_LENGTH
# REAL_CHAIN_LENGTH must be changed in sync with all other clients

**Comment by CohibAA** [comment]
While I agree that changing REAL_CHAIN_LENGTH will disconnect your from the existing pool network, it seems that changing CHAIN_LENGTH may also cause errors with downloading or sending peer shares.  I don't know why yet, but when I tried to change CHAIN_LENGTH it seems that some peers will refuse to maintain your connection if you adjust CHAIN_LENGTH to a higher value.  I wasn't willing to risk more downtime or possible lost shares to investigate further at this time.

I would suggest NOT changing either of these settings for best results.
