### ISSUE TITLE
cant auto start with freebsd

### ISSUE THREAD

**Issue by encorehu** [p2pool/p2pool#192]
i wrote a rc script on freebsd, just hope p2pool started with freebsd system boot.

there is my code:

```
#!/bin/sh

# $FreeBSD$
#
# PROVIDE: p2poold
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# p2poold_enable=YES

. /etc/rc.subr

name=p2poold
rcvar=p2poold_enable

load_rc_config $name


pidfile=/var/run/${name}.pid
command=/usr/local/bin/python /root/p2pool-master/run_p2pool.py
command_args="--bitcoind-address 127.0.0.1 --bitcoind-rpc-port 8332 --bitcoind-p2p-port 8333 --address BITCOIN_ADDRESS_BITCOIN_ADDRESS --worker-port 9332 --p2pool-port 9333 --fee 0 --give-author 0.0"

run_rc_command "$1"
```

this cant start p2pool, i must start it manually.

i guess that p2pool need bitcoind running first, i modified this rc script for more than 20 times, but whatever i modified , it didnt work.

i want to know why, and how to start p2pool on freebsd system boot.

**Comment by farsider350** [comment]
Best to install on Linux #411
