### ISSUE TITLE
Weird error when trying to run the 'make' command to install P2Pool.

### ISSUE THREAD

**Issue by GeneralDefyre** [p2pool/p2pool#204]
First off, I think P2Pool is an awesome innovation for the Bitcoin xcommunity, and I hope it grows even more!

Now on to my problem. I'm in the process of setting up a node on a HP Compaq with an Intel Core 2 Duo, and 4 GB of RAM. It is running Ubuntu Server 14.04 LTS, as it is the newest OS version.

In the instructions on the p2pool website, to install p2pool itself I must run 'make' in the 'p2pool/' directory. Here's what happens when I do:

unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: **\* [/home/mitch/p2pool/.pkg/.stamp-h] Error 1

Any help would be much appreciated!

**Comment by AkiraTakizawa** [comment]
You also need libffi in order to succesfully compile p2pool:
sudo apt-get install libffi-dev

Without it, you also get this "unable to execute 'x86_64-linux-gnu-gcc': No such file or directory" error.

**Comment by Rav3nPL** [comment]
Since when you need to compile anything else than litecoin-scrypt?

**Comment by btclambo** [comment]
I got this error whey execute make:

    "cryptography requires setuptools 18.5 or newer, please upgrade to a "

**Comment by alforro** [comment]
I got this error: 

    "cryptography requires setuptools 18.5 or newer, please upgrade to a "
After executing make, Someone have how to fix it? I am using Ubuntu 16.04, python 2.7

**Comment by GeneralDefyre** [comment]
Closing due to not having done this project in almost 4 years, haha.
@alforro Please open a new issue for your problem, as this thread hasn't been looked at in years.
