### ISSUE TITLE
p2pool - support btcd

### ISSUE THREAD

**Issue by dajohi** [p2pool/p2pool#218]
It would be nice if p2pool supported [btcd](https://github.com/conformal/btcd). btcd supports getblocktemplate (bip0022 and 0023).  btcd also supports websockets as well as the standard RPCs.

btcd doesn't have 'bitcoinaddress' in its help output, so p2pool wasn't connecting.  A local hack was:

```
--- a/p2pool/bitcoin/networks/bitcoin_testnet.py
+++ b/p2pool/bitcoin/networks/bitcoin_testnet.py
@@ -12,7 +12,7 @@ P2P_PORT = 18333
 ADDRESS_VERSION = 111
 RPC_PORT = 18332
 RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
-            'bitcoinaddress' in (yield bitcoind.rpc_help()) and
+            "" in (yield bitcoind.rpc_help()) and
             (yield bitcoind.rpc_getinfo())['testnet']
         ))
 SUBSIDY_FUNC = lambda height: 50*100000000 >> (height + 1)//210000
```

Perhaps p2pool should issue a validateaddress instead of help?

**Comment by toddfries** [comment]
Don't worry, I'm pointing my THs to btcd via p2pool. And making money.  ;-)

**Comment by gurre** [comment]
@toddfries Are you using the fix suggested by @dajohi
