### ISSUE TITLE
patron_sendmany but only for local node

### ISSUE THREAD

**Issue by derubm** [p2pool/p2pool#226]
Hi,
if i understand patron_sendmany right, i would donate to all users on p2pool network.
In case of merged mining, only the local Users would contribute to the merged mined blocks, 
so i would need a possibility to donate only to local (nodewide) Users. 

Doge, Standing in the waiting row to get merged mining, will need that. 
any chance to get that soon ?

edit:
Also it would be nice to have the possibility to (somehow) get at least a second payout address
( field password maybe ? ) 
exmaple Maincoin LTC, secondary Doge
user would then be 
LTCAddress
and password
DogeAddress
using both the payment processor (in case of secondary coin only local users)

**Comment by farsider350** [comment]
This would be nice to implement. Not sure anyone has the time or resources though.
