### ISSUE TITLE
How to compile on windows to run as self contained exe

### ISSUE THREAD

**Issue by norgan** [p2pool/p2pool#231]
I've given this a go a few times from various guides. How can we build p2pool (run_p2pool.exe) or windows including the latest twisted and zope int etc?
Alternatively (or as well as) could a new windows binary be posted to the releases?

**Comment by UdjatMiner** [comment]
I would also like a new Windows binary.  When I run the latest release in Windows, the p2pool version is reported as "unknown 7032706f6f6c2d6d6173746572".

**Comment by farsider350** [comment]
The easiest way to do it on windows these days would be to use the Windows Subsystem for Linux
Instructions can be found here #411
