### ISSUE TITLE
IPython requires Python version 2.7 or 3.3 or above. (CentOS 6.4)

### ISSUE THREAD

**Issue by ingl3** [p2pool/p2pool#236]
I have installed Python 3.3 and set .bashrc alias I am now showing 

python --version as Python 3.3 but when I run make I get error

Running setup.py (path:/root/p2pool/.pyenv/build/ipython/setup.py) egg_info for package ipython
    ERROR: IPython requires Python version 2.7 or 3.3 or above.
    Complete output from command python setup.py egg_info:
    ERROR: IPython requires Python version 2.7 or 3.3 or above.

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /root/p2pool/.pyenv/build/ipython
Storing debug log for failure in /root/.pip/pip.log
make: **\* [/root/p2pool/.cache/pyenv/pyenv-1.11.6-extras.tar.gz] Error 1
# 

Any help is greatly appreciated.

**Comment by AndreyNag** [comment]
Hi. I have ubuntu server 16.04 and python 2.7.12 but recieve same error when try to make.
`Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/pool/p2pool/.pyenv/build/cryptography
Storing debug log for failure in /home/pool/.pip/pip.log
Makefile:76: ошибка выполнения рецепта для цели «/home/pool/p2pool/.cache/pyenv/pyenv-1.11.6-extras.tar.gz»
make: *** [/home/pool/p2pool/.cache/pyenv/pyenv-1.11.6-extras.tar.gz] Ошибка 1`

**Comment by AndreyNag** [comment]
In addition content log.
`  Ignoring link https://pypi.python.org/packages/f8/70/d7bd5c9c764732d5876ad34293e1ca55b2305a73ae6fcf1312202d1a798e/cryptography-1.3.4.tar.gz#md5=defd153ed901089f5aeac6eb066d5ef7 (from https://pypi.python.org/simple/cryptography/), versi
  Using version 2.1.3 (newest of versions: 2.1.3, 2.1.2, 2.1.1, 2.1, 2.0.3, 2.0.2, 2.0.1, 2.0, 1.9)
  Downloading from URL https://pypi.python.org/packages/f3/7c/ec4f94489719803cb14d35e9625d1f5a613b9c4b8d01ee52a4c77485e681/cryptography-2.1.3.tar.gz#md5=65c0963048a88fcf725cfa265ed2fd5c (from https://pypi.python.org/simple/cryptography/)
  Storing download in cache at ./.cache/pypi/https%3A%2F%2Fpypi.python.org%2Fpackages%2Ff3%2F7c%2Fec4f94489719803cb14d35e9625d1f5a613b9c4b8d01ee52a4c77485e681%2Fcryptography-2.1.3.tar.gz
  Running setup.py (path:/home/root2pool/p2pool/.pyenv/build/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
  Removing temporary dir /home/root2pool/p2pool/.pyenv/build...
Command python setup.py egg_info failed with error code 1 in /home/root2pool/p2pool/.pyenv/build/cryptography
Exception information:
Traceback (most recent call last):
  File "/home/root2pool/p2pool/.pyenv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/root2pool/p2pool/.pyenv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/root2pool/p2pool/.pyenv/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/root2pool/p2pool/.pyenv/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/root2pool/p2pool/.pyenv/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/root2pool/p2pool/.pyenv/build/cryptography
`

**Comment by AndreyNag** [comment]
When i try to start p2pool directly error
```
Traceback (most recent call last):
  File "/home/root2pool/p2pool/run_p2pool.py", line 3, in <module>
    from p2pool import main
  File "/home/root2pool/p2pool/p2pool/main.py", line 17, in <module>
    from twisted.internet import defer, reactor, protocol, tcp
ImportError: No module named twisted

```

**Comment by farsider350** [comment]
Use the install method found here #411
