### ISSUE TITLE
share diff BTC

### ISSUE THREAD

**Issue by theseraphgabriel** [p2pool/p2pool#239]
The set share difficulty does not work with bitcoin, but works with unobtanium, terra is all I have tested and does work with those. This is what I am talking about 

Share Difficulty:   address/<number>
 Sets the share difficulty for shares that count towards a payout.

the Pseudo difficulty does work just not the set share difficulty I do not use cgminer or bfgminer I am using 2 S3's and a S1 doesn't work on any of them.

**Comment by farsider350** [comment]
Depends what diff you set it to. Setting a share diff lower than p2pools min diff will default it to the p2pools min diff. ie. p2pool min diff is 200 and you set your diff to /50 it will default to 200
