### ISSUE TITLE
Not sure where else to post... Rogue mining on Testnet.

### ISSUE THREAD

**Issue by thedmeyer** [p2pool/p2pool#257]
## Just a quick observation here.

P2Pool appears to be mining (with 97% of the hash power) on the bitcoin testnet.

On top of this, little to none of the transactions on the network are being included in the blocks...

![a8d4c5b9c1a352058e46b11a4c0a1b57](https://cloud.githubusercontent.com/assets/2959172/8368659/f4a73552-1b61-11e5-9b46-f5535725ddbf.png)

**Comment by forrestv** [comment]
Hmm. I can't really do anything about it. P2Pool is almost just like solo
mining; what would you do if some solo miner was mining 97% of testnet
blocks? Besides, you should probably be using testnet-in-a-box anyway.

**Comment by ManeBit** [comment]
Understood. And I wish I could, but the application I am working on makes use of block.io and their API
