### ISSUE TITLE
Block mined as version 3 when using XT as a backend.

### ISSUE THREAD

**Issue by SilkySmooth** [p2pool/p2pool#273]
Block # [373879](https://www.blocktrail.com/BTC/block/00000000000000000e7a10e09bcbcd921007b9abc4c8a1978ea697e91b2c5245)

This block was mined from an XT node, yet it shows the old core version.

**Comment by forrestv** [comment]
P2Pool internally limits the version to 3. What effect does this have on
Bitcoin XT? I thought that they were using a string within the coinbase to
vote, no?

**Comment by SilkySmooth** [comment]
They use a version number of something like 0x20000007. As far as I know this is what is looked for in the voting mechanism for switchover.

**Comment by Hannott** [comment]
@SilkySmooth @forrestv 

This issue should be closed.
Versions of p2pool that work with XT can be found elsewhere. https://github.com/Hannott/p2pool is one of them

**Comment by SilkySmooth** [comment]
Closing issue as a work-around is listed at http://xtnodes.com/p2pool_configuration.php and I've moved away from p2pool due to variance.
