### ISSUE TITLE
p2pool not using content-length?

### ISSUE THREAD

**Issue by drazisil** [p2pool/p2pool#275]
I'm getting 'HPE_INVALID_CONSTANT' when I try to fetch http://195.154.136.142:9332/local_stats with Node.js.

From what I understand, this error fires when data is received before the content-length header, of the data goes over the value sent by this header.

I took a look at the code and it doesn't look like p2pool is even sending that header for those urls, is that correct?

**Comment by forrestv** [comment]
P2Pool is using chunked transfer encoding instead of providing the Content-Length header. This is a feature of HTTP/1.1, which is pretty old... Your library should support this.

Try requesting http://195.154.136.142:9332/static/ . It provides a Content-Length header.

**Comment by drazisil** [comment]
Getting same error on that url as well. Claims first ch is not H. This is probably user error on my side. I'll leave open for now just in case and close after I confirm.

**Comment by forrestv** [comment]
P2Pool does do some kind of weird things to detect if a Stratum client is
connecting and provide a Stratum response instead of an HTTP one.

I'd recommend using Wireshark to see what's going on.

**Comment by drazisil** [comment]
Not easy to do when I'm running on travis. I did get it working though. I'm timing out on connection about 50% of the time, which could be p2pool derping the connection like you said. I'll look into trying to figure out if I need to toss a certain header at it to get it to behave.
