### ISSUE TITLE
Strange errors  - Clean P2Pool/Bitcoin install

### ISSUE THREAD

**Issue by Crasha** [p2pool/p2pool#278]
Hi,

I've been getting some strange errors when running the latest p2pool version (14). Opening the WEb UI throws an error, and when idling so it's downloading/verifying shares, it also throws an error. I attached a screenshot below.

Also, when I connected my miner to the pool, the shares was increasing into the hundreds as if I was getting unlimited shares, and I saw the difficulty was at 1. Obviously this isn't normal, so I'm just wondering what's going on. It works fine on Windows, but I'm running this in Linux (Ubuntu Server 14.04.3 LTS).

![p2pool errors](https://cloud.githubusercontent.com/assets/4403436/10418008/ee7f01de-7046-11e5-84f3-f761843b0c42.png)

UPDATE: It appears that issue fixed it self, however I think it needs looking into since it has never done this before on previous versions of p2pool that I have ran. I've come across a rather annoying issue now that is happening on Windows AND Linux (Screenshot 2 below). My P2Pool node keeps losing it's connection with the bitcoin client and thus making my miners beep. This happens randomly and has even got to the point where it hasn't been able to re-connect for hours. It's fine once first started, but then worsens over time, ultimately making p2pool completely useless for me to mine on.

![p2pool error 2](https://cloud.githubusercontent.com/assets/4403436/10418572/9f93926e-7056-11e5-89d1-400de12bb6ca.png)

Any ideas?

Thanks,
Owen.

**Comment by Crasha** [comment]
Hmmm. Just left it and it seems to have sorted itself out now on the Web UI and with that issue about ShareReplyError: too long.

**Comment by farsider350** [comment]
I'm fairly certain the top issue was no shares had been previously submitted.
And the bottom issue was caused by the Jtoomim hard fork as his code was changed to mine larger blocks.
#305 
#411
