### ISSUE TITLE
p2pool (version unknown)

### ISSUE THREAD

**Issue by Rav3nPL** [p2pool/p2pool#29]
I`m running p2pool on windows on python27 from sources (downloaded from git latest zip).
It is not showing version in log and on /static page.
http://91.235.254.37:9332/

**Comment by HamishMacEwan** [comment]
```
user@host:~$ cd bin/p2pool-p2pool-9c6b210/
user@host:~/bin/p2pool-p2pool-9c6b210$ python run_p2pool.py --version
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
unknown 7032706f6f6c2d7032706f6f6c2d39633662323130
```
I have the folder name, but not, it would seem, a git setup that helps with the version.  How important is it.  My miner currently reports http://192.168.1.71:9332 as Dead
