### ISSUE TITLE
No payout for Jan 10-11 2016, and only one payout on 12th.

### ISSUE THREAD

**Issue by 9cat** [p2pool/p2pool#294]
There is no payout for Jan 10-11 2016, and only one payout on 12th.

I checked the first 5 LTC miner on p2pool, and they are the same issue.

here is an example :
http://ltc.blockr.io/address/info/LeD2fnnDJYZuyt8zgDsZ2oBGmuVcxGKCLd
 http://ltc.blockr.io/address/info/LYJgT8qWXc9Ny9R4znTWX8Jb9KB9tNvjzn

Any wrong with P2Pool itself?
or could reference any issue about it.

**Comment by wrapperband** [comment]
I "reported" to Forrest analysis I did of FTC p2pool. We were able to  show, Global pool rates and shares 'appeared' to be as programmed. I can run that on Litecoin p2pool, it might give indications of problems (we suspected a separate pool attaching with low shares).
Otherwise, shares and blocks are pure chance and sometimes they should be scarce even if p2pool is significant to the 'Total' mining pool. Point me at the p2pool...

**Comment by wrapperband** [comment]
Currently LTC hash is 1500 GHash/sec  whilst the p2pool hash rate is about 15 GHash/sec.  

So far the hash v. p2pool share difficulty looks OK, see attached. The share difficulty changes with hash, but takes into account 'stratum', or building up a minimum number and difficulty of shares.
![difficulty v hash ltc p2pool14 1 2016b](https://cloud.githubusercontent.com/assets/4609536/12340978/39975b70-bb16-11e5-9f20-1af12d768455.jpg)

**Comment by wrapperband** [comment]
Just noted a missing difficulty, then two weird low values came back. I'll do the latest chart.  
   
Time                                  Global Hash                p2pool share Difficulty
2016/01/15:13:48:01:665 10069707298.762297 1.1134803588419193
2016/01/15:13:50:01:968 10066231100.938675 0.0011516259936299716
2016/01/15:13:52:02:267 10070460335.321842 1.2048868378959754
2016/01/15:13:54:01:614 10170327182.344772 1.209512208626322
2016/01/15:13:56:02:207 10132497867.776594 1.223603876099255
2016/01/15:13:58:01:465 10162723955.067608 1.2332749957658218
2016/01/15:14:00:01:750 10128476285.34168 0.0012541819461183456

**Comment by wrapperband** [comment]
Just an update on the p2pool monitoring.  

Updated chart shows Global hash rate reduced by ~50% between 
2016/01/18:06:40:01:533 12.1 GHash/s  1.1296216495733862 share diff
2016/01/18:10:04:02:242 6.08 GHash/s  0.3615285317092546 share diff

Unusually, no response from the pool at these times ( 1 sample every 2.5 min). 
2016/01/18:00:58:06:834
2016/01/18:01:00:01:874
2016/01/18:01:02:01:918
2016/01/18:01:20:01:404
2016/01/18:01:22:01:448
  
 
![difficulty v hash ltc p2pool14-18 1 2016](https://cloud.githubusercontent.com/assets/4609536/12389647/f1921cb6-bdd1-11e5-9f6a-14688686d376.jpg)

**Comment by wrapperband** [comment]
http://ltcpool.cryptal.net:9327/static/ 
Down since :
2016/01/19:04:50:01:244
