### ISSUE TITLE
Incorrect time to share estimation on web end

### ISSUE THREAD

**Issue by nullivex** [p2pool/p2pool#296]
Hello,

I am seeing the following.

CLI

```
2016-01-17 19:43:46.245314  Local: 20772GH/s in last 10.0 minutes Local dead on arrival: ~4.3% (2-7%) Expected time to share: 28.8 minutes
```

Web

```
Local rate: 20.9TH/s (4.5% DOA) Expected time to share: 6.0 minutes
```

It seems the CLI is the more correct estimation.

Anyone else see this?

**Comment by nullivex** [comment]
I am still seeing this consistently.

It appears the estimation on the web frontend is 10x smaller that the estimation on the CLI so I would think it means there is a match fudge somewhere in the render process.

**Comment by farsider350** [comment]
The Expected time to share you are seeing is "Min Diff Est Time To Share"
Using a Web Ui will help viewing of stats https://github.com/farsider350/node-stats-btc.git
