### ISSUE TITLE
Getting dead shares on a local network?

### ISSUE THREAD

**Issue by nullivex** [p2pool/p2pool#297]
Hello,

I am having an issue where I am getting about 8% dead rate. I have my miners hooked to a Brocade FWS624 I also have a Supermicro server running p2pool connected to the same switch.

My latency from pool to miner is 200 microseconds.

I am curious if this is normal.

```
Shares: 89 total (9 orphaned, 8 dead) Efficiency: 95.06%
```

I feel like the dead shares shouldnt be happening with this configuration.

Pool overview

```
Version: 15.0-11-g5090bf5

Pool rate: 1.21PH/s (15% DOA+orphan) Share difficulty: 1760000

Node uptime: 2.2 days Peers: 6 out, 0 in

Local rate: 20.8TH/s (5.0% DOA) Expected time to share: 6.1 minutes

Shares: 89 total (9 orphaned, 8 dead) Efficiency: 95.06%

Payout if a block were found NOW: 0 BTC to 14peubKaJtkUZdtycjJGbKNbLWffmM6ERV. Expected after mining for 24 hours: 0.432 BTC per block.

Current block value: 25.21699077 BTC Expected time to block: 4.7 days
```

Thanks

**Comment by forrestv** [comment]
Dead shares are due to both p2pool<->miner latency and latency internal to
the miner. With GPUs, you used to be able to tweak the size of the
workunits to decrease the internal latency, but ASICs are usually less
flexible. What miners do you have?

**Comment by nullivex** [comment]
6 x Antminer S7

**Comment by nullivex** [comment]
Is there a place I can see some p2pool peers to connect with?

**Comment by p3yot3** [comment]
http://nodes.p2pool.co/

**Comment by nullivex** [comment]
I think I sorted this out.

My bitcoind was at times saturating my local net outbound.

I put a rate limiter on my pool server and my rates are much better.

```
2016-01-18 15:16:49.429706 P2Pool: 17374 shares in chain (17378 verified/17378 total) Peers: 7 (1 incoming)
2016-01-18 15:16:49.429823  Local: 24719GH/s in last 10.0 minutes Local dead on arrival: ~1.0% (0-3%) Expected time to share: 28.7 minutes
2016-01-18 15:16:49.429874  Shares: 37 (3 orphan, 1 dead) Stale rate: ~10.8% (4-25%) Efficiency: ~115.9% (97-125%) Current payout: (0.0225)=0.0225 BTC
2016-01-18 15:16:49.429931  Pool: 1715TH/s Stale rate: 23.1% Expected time to block: 3.3 days
```
