### ISSUE TITLE
Username Questions

### ISSUE THREAD

**Issue by nullivex** [p2pool/p2pool#298]
Hello,

I was curious.

I am currently using bitcoin addresses as my miner usernames. From what I read this will send share payouts directly to the miner who found the share.

My question is if I can use usernames like [ btc address ].m45 and still maintain this functionality?

Thanks

**Comment by forrestv** [comment]
No, it's one or the other. It's recommended to configure P2Pool to pay to
one address with the `-a` option and then use descriptive miner usernames.

**Comment by nullivex** [comment]
Okay,

Thank you I am going to change this strategy then.
