### ISSUE TITLE
Does the sCrypt litecoin p2pool need to upgrade ver 16?

### ISSUE THREAD

**Issue by 9cat** [p2pool/p2pool#310]
Does the sCrypt litecoin p2pool need to upgrade ver 16?

FYR:
Changes:
- CSV compatibility
- Requires Bitcoin >=0.12.1

Several BIPs will take effect in the next few days and in order for
P2Pool to continue working without producing invalid blocks, everyone
needs to upgrade. At 50% of our hashrate upgrading, P2Pool instances
will start displaying a warning saying that an upgrade is required.
Reaching that point as quickly as possible is very important. And
then, at 95%, users that have not upgraded will be excluded. If
non-upgraded users aren't excluded before the Bitcoin changes takes
effect, P2Pool users will be subject to paying other users for invalid
work - effectively a withholding attack.

**Comment by forrestv** [comment]
It won't hurt to upgrade, but no, it's not necessary. This is a result of changes to Bitcoin Core.
