### ISSUE TITLE
Freezing during process of exchange of shares with peers.

### ISSUE THREAD

**Issue by ilsawa** [p2pool/p2pool#311]
At the time when the giant amount of transactions go through BTC network, many nodes lose their connection with the daemon.
When the connection is restored, they actively start to synchronize shares with other nodes.
I noticed that in the process of an exchange of shares with remote peers the node stops taking the job from miners.
`2016-06-29 01:38:16.266381 Processing 109 shares from 46.32.254.29:9333...
2016-06-29 01:39:56.764554 ... done processing 109 shares. New: 19 Have: 22792/~17280`
40 seconds of inactivity. It causes a significant drop of hashrate and the graphs of local rate become spiked.
![spiked](https://cloud.githubusercontent.com/assets/8270179/16430927/e7f5dcda-3d9f-11e6-942b-bb8c6282fcd3.png)

**Comment by AndreyNag** [comment]
I also observe this effect. 
Please note

**Comment by igorwhite** [comment]
A similar problem [http://poolcrypto.org:9332/static/](url)

**Comment by General-Beck** [comment]
http://87.255.26.172:9332

**Comment by KyrosKrane** [comment]
Here's an extended log where processing took so long that the watchdog triggered. I trimmed the log to about 30 seconds before the error, until about a minute after it recovered and stabilized.
[errorlog.txt](https://github.com/p2pool/p2pool/files/338201/errorlog.txt)

**Comment by AndreyNag** [comment]
f necessary, I'll post the log.
