### ISSUE TITLE
adaptive difficulty

### ISSUE THREAD

**Issue by alisadanielZQx** [p2pool/p2pool#321]
what string can one adjust in order to increase worker/default pool difficulty ? Struggling with it badly.

**Comment by veqtrus** [comment]
Use `username+difficulty` as the stratum user, e.g. `abc+4096`.

https://en.bitcoin.it/wiki/P2Pool#Useful_features

**Comment by Rav3nPL** [comment]
It is not working? max diff is 999.98xxxxx

**Comment by farsider350** [comment]
Psuedo Share diff is username+diff
and p2pool Share diif is username/diff
also combining the two will work username/diff+diff
