### ISSUE TITLE
Make P2Pool header-agnostic

### ISSUE THREAD

**Issue by str4d** [p2pool/p2pool#323]
P2Pool supports multiple different blockchain networks via a config option and a simple per-network support file. However, P2Pool assumes that all networks use the same block header format and the same GBT & Stratum protocols, which limits its compatibility to blockchains of that format.

The core logic (the GBT communication with the network node, the Stratum communication with the miner, and the `WorkerBridge` in between) should be made header-agnostic, by moving the existing header-specific code into a default implementation, and enabling blockchains with non-Bitcoin block headers to specify their own details. In addition to enabling broader network compatibility, this would help to make future changes to block headers in already-supported networks easier to handle.

**Comment by str4d** [comment]
My motivation for this is [enabling P2Pool to support Zcash](https://forum.z.cash/t/zcash-p2pool-mining-development/1051?u=str4d). I'd prefer to do this in a way that can be integrated here instead of requiring an ongoing fork (which additionally would have issues around the fact that there is already multi-network support).

**Comment by str4d** [comment]
It looks like the following areas would need to be modified or extended:

- [ ] P2Pool shares
  - The `min_header` field contains the block header (set in `get_share()` returned from `p2pool.data.*Share.generate_transaction()`), currently in a fixed format for all networks.
- [ ] `WorkerBridge`
  - Assumes the block header nonce is 32 bits.
  - Assumes the presence of `extraNonce` in the coinbase transaction, modified by the miner.
  - Probably makes other assumptions too.
- [ ] GBT protocol
  - Might already be okay? It is just called as a function, and being a key-value protocol it is easier for other networks to make changes that are compatible with the majority of the protocol than for Stratum.
  - The only place its output is used that needs modification is `WorkerBridge` AFAICT.
- [ ] Stratum protocol
  - Already its own file; specific networks can reference their own implementation and `p2pool.main` can look at the network support file to find and start the correct server.

**Comment by albabosh** [comment]
Are there any new on P2pool for z-coins ?
