### ISSUE TITLE
I would like to understand why the console is not displayed, the Current payout

### ISSUE THREAD

**Issue by Madji** [p2pool/p2pool#324]
Shares: 70 (5 orphan, 0 dead) Stale rate: ~7.1% (3-16%) Efficiency: ~106.0% (96-111%) Current payout: (0.0000)=0.0000 BTC

this is a my configuration error or a bug?

**Comment by Rav3nPL** [comment]
If you use address as username you will NOT see payout there.
Also, if node is up long time (>days) those shares can be old enough to be outside payout window.

**Comment by Madji** [comment]
what to use for workers what are the logins

**Comment by Madji** [comment]
thanks.
if you use login , then everything is displayed correctly
Shares: 1 (0 orphan, 0 dead) Stale rate: ~0.0% (0-80%) Efficiency: ~118.3% (24-119%) Current payout: (0.0007)=0.0007 BTC
