### ISSUE TITLE
Update for SegWit and Core 0.13.1

### ISSUE THREAD

**Issue by ChainQuery** [p2pool/p2pool#326]
0.13.1 has been released, I'm 99% sure there are breaking changes once SegWit is enforced...

**Comment by veqtrus** [comment]
First P2Pool segwit testnet blocks!

* https://testnet.smartbit.com.au/block/1014039
* https://testnet.smartbit.com.au/block/1014040

I will test the upgrade on my own for a few more days and then will make a PR for public testing.

> I, Paul Georgiou (veqtrus), am the owner of mz5ydTb59nk3AMPrpVtDQi2WGy7F26b8aY

`H0ppaEZDVTNITu5qZ2PYOaowurKGq87bwoU70lNHxmdNIpqV+QOvG5NrWemfV1IYZu1nvQCWKbrWJIDDb8HW7AI=`

**Comment by veqtrus** [comment]
Implementation available on #327

**Comment by forrestv** [comment]
Thanks for working on this, @veqtrus. Sorry that I've been out of the loop. Do you know when SegWit will take effect?

**Comment by btcdrak** [comment]
@forrestv You can follow adoption here https://bitcoincore.org/en/segwit_adoption/

**Comment by p3yot3** [comment]
That's a "yes" list - no surprise that bitcoincore.org forget to include those who say "no".

**Comment by farsider350** [comment]
Merged
