### ISSUE TITLE
Elimination spaces and tabs at the end of the user name

### ISSUE THREAD

**Issue by ilsawa** [p2pool/p2pool#338]
If the worker will mistakenly add a space or tab to the end of the address, it will dig to the default address.
It happens very often.
The following change can solve this problem:
In p2pool/p2pool/work.py on line 171

` user, contents2 = contents[0], contents[1:]`

Change to:

` user, contents2 = contents[0].strip(), contents[1:]`

**Comment by ChainQuery** [comment]
Huge ACK, have done this myself!

**Comment by farsider350** [comment]
New branch created: Issue Fixes
Will work on merging as many issue fixes as possible before I start a push review.
