### ISSUE TITLE
address 'vps.forre.st' not found

### ISSUE THREAD

**Issue by rmwb** [p2pool/p2pool#346]
Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: address 'vps.forre.st' not found: [Errno -2] Name does not resolve.

**Comment by p3yot3** [comment]
Been like that for years.....dev gone.

**Comment by kbirand** [comment]
any solution ?

**Comment by farsider350** [comment]
#411
