### ISSUE TITLE
P2Pool don`t work

### ISSUE THREAD

**Issue by kolonw** [p2pool/p2pool#348]
I installed everything like in readme

There is message like in link
What`s wrong?
[link](https://drive.google.com/file/d/0B2FUExckzt6jTXhUV1RfeFc4SHc/view?usp=sharing)

**Comment by forrestv** [comment]
"Bitcoin is downloading blocks"

Wait for Bitcoin to finish synchronizing.

**Comment by kolonw** [comment]
Thank You.
