### ISSUE TITLE
payments

### ISSUE THREAD

**Issue by ANdryuha174** [p2pool/p2pool#361]
Put the pool under the warrant on the site nicehash, the order was successful and all the speed for which I paid was executed, but no payments, with a pool I can not contact as I can not do what? pool: /212.45.19.162:9332 if there is someone who has that opportunity, you can contact them and say that they should pay me for 2017-11-13 12:04:00.

**Comment by farsider350** [comment]
I doubt that the pool found a block in the time you had shares active. Sorry for your loss but p2pool can sometimes take months to find a block. All public nodes are anonymous unless stated on their site.
