### ISSUE TITLE
The 'getinfo' method is excluded from the latest versions of the bitcoin core wallet

### ISSUE THREAD

**Issue by ilsawa** [p2pool/p2pool#364]
This causes an error when running p2pool

> Error while checking Bitcoin connection:
> Traceback (most recent call last):
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
>     current.result = callback(current.result, *args, **kw)
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/defer.py", line 1241, in gotResult
>     _inlineCallbacks(r, g, deferred)
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
> --- <exception caught here> ---
>   File "/opt/sha256d/p2pool-btc/p2pool/util/deferral.py", line 41, in f
>     result = yield func(*args, **kwargs)
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/sha256d/p2pool-btc/p2pool/bitcoin/helper.py", line 17, in check
>     version_check_result = net.VERSION_CHECK((yield bitcoind.rpc_getinfo())['version'])
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/usr/local/lib/pypy2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/sha256d/p2pool-btc/p2pool/util/jsonrpc.py", line 133, in _http_do
>     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
> p2pool.util.jsonrpc.NarrowError: -32601 Method not found

**Comment by KrasserBilko** [comment]
Me too, the new core isnt working with p2pool.
I try downgrading to 15.0.1 and hope it will work...

**Comment by AndreyNag** [comment]
And what we have to do?

**Comment by forrestv** [comment]
Did merging #367 fix this?

**Comment by ilsawa** [comment]
Yes, it will fix it.
