### ISSUE TITLE
unable to run the project

### ISSUE THREAD

**Issue by satyamobi** [p2pool/p2pool#366]
I cloned  the master branch and ran "make" command for installing the dependencies  and it gives me the following error:

 error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

my pip set up tools are updated too, but still facing the same issue on my  Max OS

**Comment by AndreyNag** [comment]
Ubuntu Linux 16.04 x64 same problem, but it is not fatality. Don't make, Start directly by python or pypy.

**Comment by dileep021** [comment]
i'm having the same issue on macOS. 
@AndreyNag what do you mean by Start directly by python or pypy.

**Comment by satyamobi** [comment]
@AndreyNag  I am able to start it using that, but where I can find about mining ?

**Comment by satyamobi** [comment]
@dileep021  clone and install the required dependencies , terminal just run python run_p2pool.py

**Comment by lovellzs** [comment]
@satyamobi  I just download the source ,terminal just run python run_p2pool.py ,but fail. Could you  tell me which version of  the codes you downloaded? or show me your environment. thank you!
I get the same  error  as you

**Comment by denisovdenis** [comment]
I got this error too. Spend all my Saturday trying to fix but no result. Help!

**Comment by satyamobi** [comment]
@lovellzs  @denisovdenis  i download the repo and followed README guide , and  alternative you can do this https://hash-to-coins.com/ and register and add your worker account  , stratum+tcp://hash-to-coins.com:3333, download cgminer/bgminer

**Comment by denisovdenis** [comment]
@satyamobi

> i download the repo and followed README guide

And it's work for you right now? I do the same, but nothing can happened. What Python version do you use?

**Comment by satyamobi** [comment]
version 2.7
