### ISSUE TITLE
P2Pool.org Node has lost contact with bitdoind 38 hours since last block?

### ISSUE THREAD

**Issue by thdillin** [p2pool/p2pool#371]
Are you aware that p2pool.org is not talking to bitcoind and hasn't for nearly a day? How many blocks have been missed because of this?

Warning: LOST CONTACT WITH BITCOIND for 19.9 hours! Check that it isn't frozen or dead!

http://p2pool.org:9332/static/

**Comment by ChainQuery** [comment]
> Are you aware that p2pool.org is not talking to bitcoind and hasn't for nearly a day?

I am now.

> How many blocks have been missed because of this?

Zero.

I’ll be able to take a look after the weekend.

**Comment by thdillin** [comment]
Thanks, I have another question. It appears that the last time a block was found and can be located in the blockchain was April 1, 2017. The other blocks that appear on p2pool.org are not in the blockchain. There is no block height for the discovered blocks. Was April 1, 2017 the last time a block was found, if not why aren't the newer blocks showing up with a block height. Also, when I search the main chain for the hashes that are listed they do not show up in the blockchain. Is p2Pool working correctly? I don't see that it is. We are hoping to shift a rather large miner farm over to P2Pool, but I am concerned that P2Pool isn't working correctly with bitcoin. Thanks, any help in understanding what is going on here is greatly appreciated.

**Comment by ChainQuery** [comment]
I believe it likely a problem with my code on p2pool.org, which has nothing to do with the pool itself. My node simply extracts the data and displays it on p2pool.org.

I hope to have time this week to get the data collection back up and running properly.

The best way for you to get accurate insight into the sharechain is to run a local p2pool node.

**Comment by thdillin** [comment]
I am running a local node. The local node shows transactions the same as p2pool.org I am wondering if the share-chain forked or if someone's bitcoind forked and it polluted the share-chain about 298 days ago?

Thanks for looking into this.

**Comment by scprobertsc2015** [comment]
Hi sorry new here. I am sure this is not tg correct place but I am forumlychallanged... Don't do well with social media either. Am I correct in assuming that my p2pool node is operation properly and the average block time of P2 is currently about 80 days? Or am I way off and my pool broken. I have been mining for about 250 hours on my own local node and don't see any block history. I have been a goober the last three years and mined on the big pools so not real up to speed on p2 but my dash node seems to be doing really well.  The URL is http://mm-coind192.mergermining.com:9332/ I will throw a little coin to anyone that will help out. Thanks!

**Comment by farsider350** [comment]
80days was probably correct at the time, yes.
