### ISSUE TITLE
new coins

### ISSUE THREAD

**Issue by pfreak2000** [p2pool/p2pool#372]
how can i add new altcoins ?

can anyone help me with a simple guide

**Comment by AndreyNag** [comment]
There is no universal simple guide. Most of the coin have the unical feature. Even the coin with one algo.

**Comment by pfreak2000** [comment]
thanks for the fast reply, but i will not add new algos.
i search a p2pool for Halcyon, Crowdcoin, GoByte, Vivo, Trezarcoin
but for neoscrypt i found only Mona or Vertcoin.

**Comment by farsider350** [comment]
https://bitcointalk.org/index.php?topic=457574.0
