### ISSUE TITLE
How to match the bitcoin codes with p2pool version

### ISSUE THREAD

**Issue by lovellzs** [p2pool/p2pool#374]
The Bitcoind codes and the  version update frequently，now ，I use the latest p2pool code to match  the  bitcoind which I maked from the newest bitcoin codes ，it doesn't seem to work. How can I How to match the bitcoin codes with p2pool version？ By the time or what else?

**Comment by Nageki** [comment]
If it doesn't support the new code, you should write an issue of why it doesn't support the code.
