### ISSUE TITLE
share not found

### ISSUE THREAD

**Issue by kissxrl** [p2pool/p2pool#375]
Self built Shanzhai mining pool

 Share explorer    -> Best share   ->    share not found

![1111](https://user-images.githubusercontent.com/9613121/36339151-cc143764-13f9-11e8-825d-3250f055a9ae.jpg)
![2222](https://user-images.githubusercontent.com/9613121/36339153-d09facbe-13f9-11e8-88c2-c432772d1b04.jpg)
![3333](https://user-images.githubusercontent.com/9613121/36339154-d0d9d2f4-13f9-11e8-9462-d0913a8e1e98.jpg)

**Comment by lovellzs** [comment]
你这个用的是那个浏览器页面？自己写的吗？
