### ISSUE TITLE
building 'ltc_scrypt' errror

### ISSUE THREAD

**Issue by DJMorgan** [p2pool/p2pool#377]
litecoin_scrypt
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

if anyone has this error install|:
sudo apt-get install build-essential

**Comment by DJMorgan** [comment]
sudo apt-get install build-essential

**Comment by farsider350** [comment]
Thanks for the edit
