### ISSUE TITLE
Does not support P2SH or Bech32 Payout Addresses

### ISSUE THREAD

**Issue by Nageki** [p2pool/p2pool#378]
This is particularly concerning because Bitcoin Core 16.0 generates P2SH addresses by default, so p2pool fails to run. The traceback is as follows

```
--- <exception caught here> ---
  File "/home/xxx/p2pool/p2pool/main.py", line 145, in main
    my_pubkey_hash = bitcoin_data.address_to_pubkey_hash(address, net.PARENT)
  File "/home/xxx/p2pool/p2pool/bitcoin/data.py", line 324, in address_to_pubkey_hash
    raise ValueError('address not for this net!')
exceptions.ValueError: address not for this net!

```

**Comment by rhigdon** [comment]
+1

**Comment by djames007** [comment]
Is there a fix for this?  I'm getting the same error and the "+1" response does not help at all. 

--- <exception caught here> ---
  File "/home/maddas/p2pool/p2pool/main.py", line 145, in main
    my_pubkey_hash = bitcoin_data.address_to_pubkey_hash(address, net.PARENT)
  File "/home/maddas/p2pool/p2pool/bitcoin/data.py", line 324, in address_to_pubkey_hash
    raise ValueError('address not for this net!')
exceptions.ValueError: address not for this net!

**Comment by Nageki** [comment]
@djames007 Unless you want to edit the python code to ask for an old legacy address, the only fix I can think of is using Bitcoin Core 15.0

**Comment by djames007** [comment]
@Nageki   Tested on legacy Bitcoin Core 15.0 and it works perfectly.. Uninstalled bitcoin core 16.0 and used the same/saved data Blocks, 15 hours of disk data sync, no corruption, p2pool up and running!  Good call on this one!

**Comment by digitalwav** [comment]
This issue just showed up with the latest version of Vertcoin Core v0.13.2.0-bc60034 (64-bit) as well. The networks are starting to default to a new address format and P2Pool hasn't caught up yet...

**Comment by farsider350** [comment]
Go to Core wallet Console and type
getnewaddress "" legacy
copy the new address into p2pool/data/bitcoin/cached_payout_address

**Comment by LDiga** [comment]
Th

> Go to Core wallet Console and type
> getnewaddress "" legacy
> copy the new address into p2pool/data/bitcoin/cached_payout_address

Мне это помолло!
