### ISSUE TITLE
2018-03-14 12:55:04.737427 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!

### ISSUE THREAD

**Issue by YankeeTube** [p2pool/p2pool#381]
i want to start on p2pool.
somebody help me..!

and then my altcoin .conf :
rpcuser=[username] 
rpcpassword=x
rpcport=[portnumber]
listen=1
daemon=1
server=1
dnsseed=0
addnode=192.168.0.101
addnode=192.168.0.102

**Comment by AndreyNag** [comment]
Try to add in .conf 
```
rpcallowip=127.0.0.1
rpcbind=127.0.0.1

```

**Comment by pavel190781** [comment]
доброго времени суток .  я могу подключиться только к московскому узлу. перепробовал все операторов связи.   пингуется только московский  и еще несколько штук но там пинг 160 и выше. а ближайший ко мне Питер не пергуется. кто нибуть помогитеpavel190781@gmail.com
