### ISSUE TITLE
Not an issue just a good oldie question

### ISSUE THREAD

**Issue by maHost** [p2pool/p2pool#382]
@forrestv What happens when I connect many workers with the same payout address?
Does each worker works on its own share with the specific share diff or p2pool splits the share diff between them and they mine all together towards the same share?

Example:
3 miners with same payout address mining at a /6000 diff. -> Is each miner mining own its own share are /6000 or are they mining torwards the same share and each is mining at a /2000 diff?

Just very curious about that. That question links to another one related how the hashrate shows up and time to share decreases with multiple miners are using the same payout. But that is for another time! ;)

Thank you so much,

**Comment by forrestv** [comment]
They are all trying to mine the same share. Mining is a random, memoryless
process; it doesn't really make sense to "work together towards a single
share".

The difficulty given to workers in the difficulty specified in the miner
username and doesn't depend on the number of miners working.

**Comment by maHost** [comment]
Thank you for the quick reply @forrestv.
So it is safe to say that each miner even that it has the same payout address is mining at a given /sharediff instead of splitting it?
So If I have 2 miners with same payout address, can I set one at /1000 share diff and the other at /5000 and they will mine at these diffs each?

Thank you and sorry if I'm not getting it! ;)
