### ISSUE TITLE
how to settings for SANE_TARGET_RANGE?

### ISSUE THREAD

**Issue by YankeeTube** [p2pool/p2pool#385]
hello.

I wonder how to set the SANE_TARGET _ RANGE.

can u tell me what to look at in my coin file???

bitcoin is  SANE_TARGET_RANGE = (2 ** 256 // 2 ** 32 // 1000000 - 1, 2 ** 256//2 ** 32 - 1)
litecoin is SANE_TARGET_RANGE = (2 ** 256 //1000000000 - 1, 2 ** 256//1000 - 1)
dash     is SANE_TARGET_RANGE = (2 ** 256 // 2 ** 32 // 1000000 - 1, 2 ** 256//2 ** 32 - 1)

Why are they different?
What kind of file can I look at to get information about that?
main.cpp?
chainparams.cpp???

pls somebody help me~~~!

**Comment by farsider350** [comment]
You can set psuedo share with walletaddress+***
You set pool diff with walletaddress/***
Or combine the two walletaddress/320+64000

Sane targets in the code shouldn't be adjusted for Mainnet applications.

**Comment by YankeeTube** [comment]
hey farsider350 
i want to SANE_TARGET_RANGE but i don't want psuedo settings.
Why are you referring to pseudo?
pseudo settings is  similar to the sane_target_range?

**Comment by YankeeTube** [comment]
> 

> You can set psuedo share with walletaddress+***
> You set pool diff with walletaddress/***
> Or combine the two walletaddress/320+64000
> 
> Sane targets in the code shouldn't be adjusted for Mainnet applications.

hey farsider350
i want to SANE_TARGET_RANGE but i don't want psuedo settings.
Why are you referring to pseudo?
pseudo settings is similar to the sane_target_range?
