### ISSUE TITLE
Sometimes the mining stops.

### ISSUE THREAD

**Issue by YankeeTube** [p2pool/p2pool#386]
i'm just test for p2pool
but my p2pool has a been so serious problem.

my environment setting is 
only one p2pool.
only one ccminer.

as my proceed to mining in 1 hour
After the difficulty has surged and,
About ten minutes are stagnant.

why does so happening?
u know?

If you know, please give me a solution
pls. somebody help me!!!!!!

**Comment by AndreyNag** [comment]
First of all you have to sincronise sharechain. 
Second you have to start to mine with low miner power. 
P2pool node have some time to proceed difficalty what miner need. For begining  you will see high DOA.  You'll see low DOA in a while.

**Comment by YankeeTube** [comment]
How do you synchronize on p2pool.?
