### ISSUE TITLE
Will not run due to  RPC connection

### ISSUE THREAD

**Issue by Gustown** [p2pool/p2pool#390]
Installed, downloaded all the required programs.

Get this error:
Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username 'bitcoinrpc'...
Error while checking Bitcoin connection:
Traceback (most recent call last):
Then a bunch of errors that I assumed are due to the connection not being successful. Any ideas?

**Comment by farsider350** [comment]
Make sure wallet is fully synced and has a filled conf file.
