### ISSUE TITLE
bitcoind-config-path on another SBC

### ISSUE THREAD

**Issue by bluciano2** [p2pool/p2pool#393]
I have 2 Single Board Computer with Debian 9 stretch, 
n.1 SBC running bitcoin full node (192.168.0.4)
n.2 SBC running p2pool (192.168.0.5)
python run_p2pool.py --bitcoind-address 192.168.0.4 --bitcoind-rpc-port 8335 --bitcoind-config-path ....
How can I write --bitcoind-config-path to 192.168.0.4/root/.bitcoin/bitcoin.conf
--bitcoind-config-path: seems working only as local host bitcoin node,not to another machine bitcoin  node

**Comment by forrestv** [comment]
You don't need --bitcoind-config-path if you provide the address, RPC port,
username, and password arguments.
