### ISSUE TITLE
JSONRPC server handles only POST requests

### ISSUE THREAD

**Issue by Mentors4EDU** [p2pool/p2pool#396]
I have both the Dashd configs and the Litecoin configs running when I run P2Pool. When I just had the Dashd configs, the UI and program would load up at local host. After I create a configuration file for Litecoin and added the module to its networks, now it says, "JSONRPC server handles only POST requests" when you go on localhost.
Even when I run the command:

`python2.7 run_p2pool.py --net litecoin --merged http://DashRPCUserName:DashRPCPass@localhost:7902`

I still run into the same error

Is there a certain configuration that I need for merged mining for both of them to show up and the web static UIs to load? Any help would be greatly appreciated

**Comment by Mentors4EDU** [comment]
Even if I activate the merged mining, it still doesn't fully explain the post requests error. Are the two related?

**Comment by farsider350** [comment]
You can't merge mine Dash and Litecoin, they are two completely different algorithms.
Try merge mining Doge with Litecoin or maybe Cann Coin with Dash.

**Comment by farsider350** [comment]
@Mentors4EDU 

If you run two instances of p2pool it will work as Litecoin and Dash use different ports ie. LTC 9327 Dash 7903
I would personally use https://github.com/dashpay/p2pool-dash for your Dash p2pool
and https://github.com/jtoomim/p2pool for Litecoin as J Toomim's Sharechain is now the largest and most used. Run a Doge wallet along side your Litecoin and merge mine to that aswell.

You can find info on setting up the Litecoin p2pool using PYPY here:
https://forum.bitcoin.com/pools/p2pool-decentralized-dos-resistant-trustless-censorship-resistant-pool-t69932-120.html

**Comment by Mentors4EDU** [comment]
Is there a way to run both instances on local Host or the same static IP, just binding different ports? 

Also needs to be entirely different directories I assume of P2Pool?

**Comment by farsider350** [comment]
Since they use separate p2p ports that is the way I see it working, using separate directories will just ensure that the 2 pools arn't using each others resources. If that will not work, setup a virtual machine for the second p2pool with its own IP.

**Comment by Mentors4EDU** [comment]
Yes, I still do run into a few binding issues when trying to connect. Since both instances seem to connect to bitcoind rpc on the same port, and both are trying to show the stats at 127.0.0.1:7903. Any way to change that configuration wise? If so then the two instances thing can work for me? @farsider350

**Comment by Mentors4EDU** [comment]
Thanks for the help!
