### ISSUE TITLE
 Is "p2pool" abandoned?

### ISSUE THREAD

**Issue by joenhon** [p2pool/p2pool#400]
Testing bitcoind RPC connection to 'http://192.168.0.90:18548/' with username '1111'...
2018-09-06 16:09:08.185000 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
![image](https://user-images.githubusercontent.com/39330202/45145238-c9c2f800-b1f2-11e8-81da-a17e6dfcc7f0.png)

**Comment by farsider350** [comment]
Last commit wasn't that long ago, abandoned to the point that updates get added as needed and issues arn't a priority as the code works fine. If you prefer a more active developer who is maintaining this p2pool in his own repository you can also try https://github.com/jtoomim/p2pool Active development is occurring in the 1mb_segwit branch.
