### ISSUE TITLE
Payouts if a block were found NOW:

### ISSUE THREAD

**Issue by faca5** [p2pool/p2pool#408]
Hello.

I have one question?

On "http://127.0.0.1:9332/static/", I got this

"Payout if a block were found NOW: 0 BTC to *** . Expected after mining for 24 hours: BTC per block."
Why BTC is still 0?

and
"Payouts if a block were found NOW:
1Kz5QaUPDtKrj5SqW5tFkn7WZh8LmQaQi4 | 12.70208732
Total | 12.70208732
Where P2POOL found this bitcoin address?

**Comment by farsider350** [comment]
That would be the address of the wallet your p2pool is connected to. It's the address fees go to. Look in the wallet your using for p2pool to find this address labelled as "p2pool".
https://github.com/jtoomim/p2pool.git is a more upto date p2pool.

**Comment by faca5** [comment]
Thank you.
