### ISSUE TITLE
Extremely High DOA + Payout Time

### ISSUE THREAD

**Issue by Mentors4EDU** [p2pool/p2pool#416]
My question is, especially on my P2Pool node, why is the DOA extremely high? Also the payout time seems to be unstable with some days saying 15 days to block and then switching to 29 days when adding a peer before going back down. I am on the Jtoomim network and had slightly similar problems with the main network. We don't get paid for shares until a block is hit but the estimated time to block seems inconsistent. The DOA also seems irregularly high.

I am connected to my endpoint and with the Dash P2Pool, I never had a problem like what I am having now with Bitcoin. There are times in the day where the DOA goes down to 19% but keeps spiking towards the higher DOA rates. We have extremely fast WiFi in our area and are running a Jtoomim node on a server with Intel(R) Xeon(R) CPU X5650 @ 2.67GHz, 24 cores. The static IP is connected through webmin and nothing is wrong with what we are running, because the Dash one works perfectly.

My question is why is the DOA unusually high and the payout inconsistent? Someone can't expect that the network takes 3 weeks to load if the time in reality is much higher. Connected to my endpoint, we are running 50+ antminers and sometimes up to 70 antminers who have expected to receive a payment of over $1.2 grand for the past few weeks. We don't know when our payouts are expected anymore or what is going on with the network to cause it to have these inconsistencies. 

A DOA that is over 50% is really high and the payouts actually went down or haven't been updated in the UI for the past two days which seems like irregular behavior.
![screenshot from 2018-10-03 15-55-57](https://user-images.githubusercontent.com/12502053/46436232-5f847100-c726-11e8-964e-4312b309c288.png)
![screenshot from 2018-10-03 16-07-22](https://user-images.githubusercontent.com/12502053/46436268-70cd7d80-c726-11e8-8a72-ba5c7cdbddfa.png)

**Comment by Mentors4EDU** [comment]
@jtoomim @forrestv @farsider350

**Comment by Mentors4EDU** [comment]
Another problem is the pool had up-time for 20 days and now still says 36 days to block. Block time is entirely inconsistent with us expecting it to have been 19 days. None of our miners or us know when the payout is coming (if any) because of this inconsistency.
![screenshot from 2018-10-05 15-00-53](https://user-images.githubusercontent.com/12502053/46554986-f7fa2d00-c8af-11e8-8d60-11c431404626.png)

**Comment by jtoomim** [comment]
Your node is unable to keep up with the load for some reason or another. I recommend that you not mine on a node if you're getting >5% DOAs. Getting 25% DOA is absurd. 

> 2.67GHz
This part matters

> 24 cores
This part does not matter.

Have you checked your RAM? Are you running out of free RAM, maybe? What are your GBT latencies? If you use a utility like top or htop, what does it say about your CPU usage? Is a single core getting pegged at 100% for at least a second at a time?

**Comment by jtoomim** [comment]
If you're using my code, the correct place to post an issue is on my github.

**Comment by Mentors4EDU** [comment]
> Your node is unable to keep up with the load for some reason or another. I recommend that you not mine on a node if you're getting >5% DOAs. Getting 25% DOA is absurd.
> 
> > 2.67GHz
> > This part matters
> 
> > 24 cores
> > This part does not matter.
> 
> Have you checked your RAM? Are you running out of free RAM, maybe? What are your GBT latencies? If you use a utility like top or htop, what does it say about your CPU usage? Is a single core getting pegged at 100% for at least a second at a time?

@jtoomim  Thank you for the response,
Problem I am wondering is why is the time to block increasing all the time in the terminal, as this makes no sense. Also from what I am seeing, no overload including only 16.6% of the memory being used. There is one CPU out of the 24 that has full usage, but not sure if that is what would contribute to all of these issues.
![screenshot from 2018-10-05 18-01-00](https://user-images.githubusercontent.com/12502053/46562130-b924a100-c8c8-11e8-8b82-320fc7025ed6.png)

**Comment by jtoomim** [comment]
Yes, having one core maxed out will cause all of your issues. p2pool is single-threaded, and can never use more than one core. If one core is maxed out as consistently as yours is, that means that p2pool is always behind in the work that it needs to do.

Time to block is increasing because not all of the work done by your miners is being accepted by your node. This is what the high DOA rates are showing. This is because your CPU is not able to keep up.

Are you using pypy or CPython? If you're using CPython, don't use CPython. pypy is about 3x faster.

**Comment by Mentors4EDU** [comment]
> Yes, having one core maxed out will cause all of your issues. p2pool is single-threaded, and can never use more than one core. If one core is maxed out as consistently as yours is, that means that p2pool is always behind in the work that it needs to do.
> 
> Time to block is increasing because not all of the work done by your miners is being accepted by your node. This is what the high DOA rates are showing. This is because your CPU is not able to keep up.
> 
> Are you using pypy or CPython? If you're using CPython, don't use CPython. pypy is about 3x faster.

@jtoomim 
I ran the python2.7 run_p2pool.py command instead of pypy. I am wondering if running pypy could fix this. My problem is if I restart the node, what happens to the previous shares or payout history?

**Comment by jtoomim** [comment]
python2.7 is CPython. Don't use CPython on BTC, or else you'll have these problems. Use pypy as described in the installation instructions:

https://forum.bitcoin.com/pools/p2pool-decentralized-dos-resistant-trustless-censorship-resistant-pool-t69932.html#p142434

**Comment by jtoomim** [comment]
> My problem is if I restart the node, what happens to the previous shares or payout history?

No revenue is lost. Your node won't display the shares that it mined during previous launches of the p2pool software, but you will still get paid for those shares. You will even get paid for shares if your node is offline when someone else on p2pool finds a block, as long as you have some shares within the last 8640 shares in the share chain (i.e. about 3 days).

**Comment by jtoomim** [comment]
What I said about the time-to-block earlier was incorrect. I didn't realize you were mining BTC. The time to block is based on the amount of hashrate that the whole p2pool network has and the block difficulty. It is NOT based on how long people have been mining since the last block. The 36 day time to block is just because p2pool on BTC has a very small portion of the total BTC hashrate. That has nothing to do with your node's operation.

**Comment by Mentors4EDU** [comment]
> > My problem is if I restart the node, what happens to the previous shares or payout history?
> 
> No revenue is lost. Your node won't display the shares that it mined during previous launches of the p2pool software, but you will still get paid for those shares. You will even get paid for shares if your node is offline when someone else on p2pool finds a block, as long as you have some shares within the last 8640 shares in the share chain (i.e. about 3 days).

Okay thanks for that information

**Comment by Mentors4EDU** [comment]
> What I said about the time-to-block earlier was incorrect. I didn't realize you were mining BTC. The time to block is based on the amount of hashrate that the whole p2pool network has and the block difficulty. It is NOT based on how long people have been mining since the last block. The 36 day time to block is just because p2pool on BTC has a very small portion of the total BTC hashrate. That has nothing to do with your node's operation.

@jtoomim Awesome, thanks
If the miners got disconnected for a few minutes after restarting the pool would they all need to reconnect or once the pool is online, if they are still running the mining program it reconnects automatically
