### ISSUE TITLE
can this use to miner bsv

### ISSUE THREAD

**Issue by zhfnjust** [p2pool/p2pool#420]

**Comment by farsider350** [comment]
I'd recommend using https://github.com/jtoomim/p2pool/tree/1mb_segwit
as it is a more upto date p2pool,
and then use this guide to create the bsv p2pool.
https://bitcointalk.org/index.php?topic=457574.0

**Comment by farsider350** [comment]
If you get it running you could post a link to it here for more peers and adoption of your code.

**Comment by zhfnjust** [comment]
thanks, i will try
