### ISSUE TITLE
No Litecoin Peers.

### ISSUE THREAD

**Issue by LinuXperia** [p2pool/p2pool#424]
Hi.
When i run P"POOL to connect to my Litecoin Server on the LAN Address xx.xx.xx.xx
everything works but P2POOL can not find any PEERS even after Hours.

How can this Problem with Peers be solved ?
I tryed adding some additional P2POOL nodes using the flag "-n" but this did also not work.

Please tell me how to solve this Problem with no Finding Peers so am able to get Litecoin working with P2POOL on my side.

**Comment by farsider350** [comment]
As far as I know the p2pool your using is not being used by many, if any other nodes for Litecoin.
Try using this p2pool referenced here #411
