### ISSUE TITLE
Historical P2Pool sharechain data

### ISSUE THREAD

**Issue by alexeiZamyatin** [p2pool/p2pool#425]
Hi! I'm a PhD student at Imperial College London and have been doing some security analysis of decentralized mining pools.
I was wondering if anyone has (and is willing to share) historical sharechain data? i.e., submitted shares/weak blocks . That would very helpful!
Thanks!

**Comment by forrestv** [comment]
Hi Alexi,

As far as I know, there is no total sharechain record for P2Pool. P2Pool
nodes only remember the last week of sharechain shares. It might be
possible to find some historical data from nodes that stopped running, but
it's definitely impossible to reconstruct the full chain.

However, it is possible to see all the block solutions that P2Pool created
by searching the Bitcoin blockchain for all blocks that have a generation
transaction that includes an output to 1Kz5QaUPDtKrj5SqW5tFkn7WZh8LmQaQi4
(the P2Pool donation address). Each block's generation transaction has an
output for each member of the pool active at that time.

Good luck with your research!

**Comment by alexeiZamyatin** [comment]
Hi, 
Thanks for the reply! Yeah, I was hoping that maybe someone persisted old sharechain blocks. Well, I'll keep looking.

**Comment by farsider350** [comment]
If you are only after historical data and don't mind doing the research based on 2 year old and previous blocks you will find block data from and before April 1st 2017 here, http://p2pool.org/stats/

**Comment by alexeiZamyatin** [comment]
Any chance of the P2Pool data here - http://p2pool.org/stats/ - being restored ?
