### ISSUE TITLE
P2Pool Error

### ISSUE THREAD

**Issue by MrStrong0** [p2pool/p2pool#430]
I am trying to setup P2Pool and I am following the guide on the website, however, when I reached step 2 I am facing an error.
When I execute run_p2pool.exe I get this error:
p2pool.util.jsonrpc.NarrowError: -1 Block not available (pruned data)

**Comment by forrestv** [comment]
You need a full, not a pruned node. Also, P2Pool is mostly entirely
defunct, FYI.

**Comment by red0bear** [comment]
@forrestv , Archive this code and build new one ?

**Comment by farsider350** [comment]
> 
> 
> @forrestv , Archive this code and build new one ?

#411
