### ISSUE TITLE
P2pool help

### ISSUE THREAD

**Issue by AgroCoin** [p2pool/p2pool#432]
Hi I would like to know if you can help me make a p2pool for the currency I work on I am not satisfied with the pool I will leave a link attached to the wallet if you need.
https://github.com/AgroCoin/agrocoin-0.15.1-

**Comment by farsider350** [comment]
There is no source code in that link. Need source, not binaries.

**Comment by AgroCoin** [comment]
https://github.com/AgroCoin/AgroCoin this is source code

**Comment by farsider350** [comment]
If this is still needed contact me here https://discord.gg/e8tk9mj6cD
