### ISSUE TITLE
Getting a bunch of `undefined reference to` when running setup.py in litecoin_scrypt

### ISSUE THREAD

**Issue by rowisahub** [p2pool/p2pool#433]
The error

`
R:\p2pool\p2pool\litecoin_scrypt>C:\Python27\python.exe setup.pyc build --compile=mingw32 install
running build

running build_ext

building 'ltc_scrypt' extension

N:\mingw\bin\gcc.exe -mdll -O -Wall -I. -IC:\Python27\include -IC:\Python27\PC -c scryptmodule.c -o build\temp.win-amd64-2.7\Release\scryptmodule.o

scryptmodule.c: In function 'scrypt_getpowhash':

scryptmodule.c:15:5: warning: implicit declaration of function 'scrypt_1024_1_1_256' [-Wimplicit-function-declaration]
     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
     ^~~~~~~~~~~~~~~~~~~

N:\mingw\bin\gcc.exe -mdll -O -Wall -I. -IC:\Python27\include -IC:\Python27\PC -c scrypt.c -o build\temp.win-amd64-2.7\Release\scrypt.o

writing build\temp.win-amd64-2.7\Release\ltc_scrypt.def

N:\mingw\bin\gcc.exe -shared -s build\temp.win-amd64-2.7\Release\scryptmodule.o build\temp.win-amd64-2.7\Release\scrypt.o build\temp.win-amd64-2.7\Release\ltc_scrypt.def -LC:\Python27\libs -LC:\Python27\PCbuild\amd64 -LC:\Python27\PC\VS9.0\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\ltc_scrypt.pyd

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0x1e): undefined reference to `_imp__PyArg_ParseTuple'

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0x3b): undefined reference to `_imp__PyMem_Malloc'

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0x4a): undefined reference to `_imp__PyString_AsString'

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0x7e): undefined reference to `_imp__Py_BuildValue'

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0x89): undefined reference to `_imp__PyMem_Free'

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0xd0): undefined reference to `_imp__Py_InitModule4'

collect2.exe: error: ld returned 1 exit status

error: command 'N:\\mingw\\bin\\gcc.exe' failed with exit status 1
`
im not sure why this is happening

**Comment by forrestv** [comment]
This seems to be some sort of compiler or library 32/64-bit mismatch issue. Please see the following seemingly related articles:

* https://stackoverflow.com/questions/15029519/error-lnk2001-unresolved-external-symbol-imp-py-initmodule4
* https://bugs.python.org/issue15772

**Comment by rowisahub** [comment]
@forrestv do you know what i could do to fix this? i have followed the links, but it always gives me the same error

**Comment by rowisahub** [comment]
New error
`
running build

running build_ext

building 'ltc_scrypt' extension

creating build

creating build\temp.win-amd64-2.7

creating build\temp.win-amd64-2.7\Release

N:\mingw2\mingw64\bin\gcc.exe -mdll -O -Wall -I. -IC:\Python27\include -IC:\Python27\PC -c scryptmodule.c -o build\temp.win-amd64-2.7\Release\scryptmodule.o

scryptmodule.c: In function 'scrypt_getpowhash':
scryptmodule.c:15:5: warning: implicit declaration of function 'scrypt_1024_1_1_256' [-Wimplicit-function-declaration]
     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
     ^~~~~~~~~~~~~~~~~~~

N:\mingw2\mingw64\bin\gcc.exe -mdll -O -Wall -I. -IC:\Python27\include -IC:\Python27\PC -c scrypt.c -o build\temp.win-amd64-2.7\Release\scrypt.o

writing build\temp.win-amd64-2.7\Release\ltc_scrypt.def

creating build\lib.win-amd64-2.7

N:\mingw2\mingw64\bin\gcc.exe -shared -s build\temp.win-amd64-2.7\Release\scryptmodule.o build\temp.win-amd64-2.7\Release\scrypt.o build\temp.win-amd64-2.7\Release\ltc_scrypt.def -LC:\Python27\libs -LC:\Python27\PCbuild\amd64 -LC:\Python27\PC\VS9.0\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\ltc_scrypt.pyd

build\temp.win-amd64-2.7\Release\scryptmodule.o:scryptmodule.c:(.text+0xbe): undefined reference to __imp_Py_InitModule4

collect2.exe: error: ld returned 1 exit status

error: command 'N:\\mingw2\\mingw64\\bin\\gcc.exe' failed with exit status 1
`
