### ISSUE TITLE
Trying to run with a different coin then supported

### ISSUE THREAD

**Issue by SebastianD20** [p2pool/p2pool#436]
Hey, I was wondering if you could give me a bit more info on the required info to make p2pool work with a different altcoin. The coin I'm trying to use is a hard fork of LTC. I was wondering if you'd possibly be able to tell me what its looking for when it asks for the identifier and prefix. I'm assuming the prefix is pch message start, encoded in hex? But I'm not sure what the identifier would be. Do you have a discord or someway to possibly help? I could pay you in btc if you wouldn't mind walking me through it. Thank you.

**Comment by farsider350** [comment]
I'll happily make a p2pool for your coin. Share the coins info here or at this discord. https://discord.gg/e8tk9mj6cD

**Comment by farsider350** [comment]
Closing
